[build]
  command = "npm run build"
  publish = ".next"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"


[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://cookbook-backend-xpm1.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
